# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
if Rails.env == "development"
  100.times do |i|
    user = User.find(1)
    user.tasks.create!(title: "test#{i + 1}", weight: "10", rep: "10", set_count: "2")
  end

  #タスクタイトル作成時にセレクトボックスでプルダウンメニューで表示される筋トレメニュー一覧
  Title.create!(title_name: "ベンチプレス")
  Title.create!(title_name: "インクラインベンチ")
  Title.create!(title_name: "デクラインベンチ")
  Title.create!(title_name: "プルオーバー")
  Title.create!(title_name: "ダンベルプレス")
  Title.create!(title_name: "ダンベルフライ")
  Title.create!(title_name: "インクライン・ダンベルプレス")
  Title.create!(title_name: "インクライン・ダンベルフライ")
  Title.create!(title_name: "デクライン・ダンベルプレス")
  Title.create!(title_name: "ダンベル・プルオーバー")
  Title.create!(title_name: "ケーブル・クロスオーバー")
  Title.create!(title_name: "プッシュアップ")
  Title.create!(title_name: "ディップス")
  Title.create!(title_name: "ベントオバーローイング")
  Title.create!(title_name: "リバースグリップ・ベントオーバーロー")
  Title.create!(title_name: "Tバーローイング")
  Title.create!(title_name: "デッドリフト")
  Title.create!(title_name: "グッドモーニング")
  Title.create!(title_name: "ワンアーム・ダンベルローイング")
  Title.create!(title_name: "ラットプルダウン")
  Title.create!(title_name: "シーテッド・ケーブルローイング")
  Title.create!(title_name: "ストレートアーム・ラットプルダウン")
  Title.create!(title_name: "チンニング")
  Title.create!(title_name: "バーベルスクワット")
  Title.create!(title_name: "ハックスクワット")
  Title.create!(title_name: "ルーマニアン・デッドリフト")
  Title.create!(title_name: "バーベルランジ")
  Title.create!(title_name: "スタンディングカーフレイズ")
  Title.create!(title_name: "ダンベルスクワット")
  Title.create!(title_name: "ダンベルランジ")
  Title.create!(title_name: "カーフレイズ")
  Title.create!(title_name: "カーフレイズ")
  Title.create!(title_name: "レッグエクステンション")
  Title.create!(title_name: "レッグ・カール")
  Title.create!(title_name: "レッグ・プレス")
  Title.create!(title_name: "スクワット")
  Title.create!(title_name: "シッシー・スクワット")
  Title.create!(title_name: "ランジ")
  Title.create!(title_name: "カーフレイズ")
  Title.create!(title_name: "バーベルカール")
  Title.create!(title_name: "シーテッドカール")
  Title.create!(title_name: "プリーチャーカール")
  Title.create!(title_name: "ダンベルカール")
  Title.create!(title_name: "シーテッド・ダンベルカール")
  Title.create!(title_name: "インクライン・ダンベルカール")
  Title.create!(title_name: "コンセントレーションカール")
  Title.create!(title_name: "ハンマーカール")
  Title.create!(title_name: "プリーチャーカール")
  Title.create!(title_name: "ケーブルカール")
  Title.create!(title_name: "ハイプーリーカール")
  Title.create!(title_name: "トライセプスエクステンション")
  Title.create!(title_name: "フレンチプレス")
  Title.create!(title_name: "ナロウベンチプレス")
  Title.create!(title_name: "ワンアーム・フレンチプレス")
  Title.create!(title_name: "トライセプス・キックバック")
  Title.create!(title_name: "ラットマシン・プレスダウン")
  Title.create!(title_name: "ワンアーム・トライセップス・プレスダウン")
  Title.create!(title_name: "リバース・プッシュアップ")
  Title.create!(title_name: "ナロウプッシュアップ")
  Title.create!(title_name: "ショルダーフロントプレス")
  Title.create!(title_name: "ショルダーバックプレス")
  Title.create!(title_name: "バーベルフロントレイズ")
  Title.create!(title_name: "バーベルアップライトロウ")
  Title.create!(title_name: "バーベルシュラッグ")
  Title.create!(title_name: "ダンベル・ショルダープレス")
  Title.create!(title_name: "リーニングダンベル・レイズ")
  Title.create!(title_name: "フロントレイズ")
  Title.create!(title_name: "サイドレイズ")
  Title.create!(title_name: "シーテッド・サイドレイズ")
  Title.create!(title_name: "ベントオーバー・リアレイズ")
  Title.create!(title_name: "ダンベルアップライトロウ")
  Title.create!(title_name: "ダンベルシュラッグ")
  Title.create!(title_name: "ケーブル・サイドレイズ")
  Title.create!(title_name: "ケーブル・リアレイズ")
  Title.create!(title_name: "デクライン・ロシアンツイスト")
  Title.create!(title_name: "サイドベント")
  Title.create!(title_name: "ケーブル・クランチ")
  Title.create!(title_name: "ケーブル・サイドベント")
  Title.create!(title_name: "クランチ")
  Title.create!(title_name: "シットアップ")
  Title.create!(title_name: "レッグレイズ")
  Title.create!(title_name: "ハンキングニーレイズ")
  Title.create!(title_name: "リストカール")
  Title.create!(title_name: "リバースリストカール")
  Title.create!(title_name: "リバースカール")

end